apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: dev-get-test
  namespace: dev-get-test
spec:
  clusters:
  - cluster: gke-dev-dis-app-engine
    region: southamerica-east1
  - cluster: gke-dev-get-app-engine
    region: southamerica-east1
  template:
    spec:
      ports:
      - port: 80
        targetPort: 5678
        protocol: TCP
