apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-master-engine
  namespace: mcs-demo
spec:
  hosts:
  - hello-master-engine.mcs-demo.global
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hello-master-engine.mcs-demo.global
        port:
          number: 80
      weight: 100
